spring:
  redis:
    host: 127.0.0.1
    port: 6379
  # database:
  # password:
  cache:
    type: redis # 指定缓存类型,一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
    redis:
      time-to-live: 60000 #全局设置缓存过期时间，单位毫秒