spring:
  rabbitmq:
    addresses: 192.168.46.88
    port: 5672
    username: root
    password: root
    virtual-host: /demo-rabbitmq-springboot
    publisher-confirms: true
    publisher-returns: true
#    listener:
#      simple:
#        acknowledge-mode: manual 全局手动应答