server:
  # 为了方便启动时设置虚拟机参数
  port: ${SPORT:10001}
spring:
  application:
    name: demo-springcloud-zuul-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${NEXTPORT:${server.port}}/eureka
    register-with-eureka: true
    fetch-registry: true