server:
  port: 9001
spring:
  application:
    name: demo-springcloud-zuul-service-user
  jackson:
    date-format: YYYY-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}