server:
  port: 8081
spring:
  application:
    name: demo-springcloud-helloworld-consumer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
